name: simple-streamlit
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - matplotlib
    - streamlit
    - scikit-learn
    - boto3
    - ipykernel
    - plotly==5.17.0
    - plotly-express==0.4.1
