name: simple-streamlit
dependencies:
  - python=3.10
  - pip
  - pip:
    - ﻿boto3==1.29.4
    - ﻿botocore==1.32.4
    - ﻿dash==2.13.0
    - ﻿dash-core-components==2.0.0
    - ﻿dash-html-components==2.0.0
    - ﻿dash-table==5.0.0
    - ﻿fastjsonschema @ file:///C:/ci_311/python-fastjsonschema_1679500568724/work
    - ﻿GitPython==3.1.40
    - ﻿json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
    - ﻿jsonpatch @ file:///tmp/build/80754af9/jsonpatch_1615747632069/work
    - ﻿jsonpointer==2.1
    - ﻿jsonschema @ file:///C:/b/abs_d1c4sm8drk/croot/jsonschema_1699041668863/work
    - ﻿jsonschema-specifications @ file:///C:/b/abs_0brvm6vryw/croot/jsonschema-specifications_1699032417323/work
    - ﻿pandas @ file:///C:/b/abs_81b3npjrl8/croot/pandas_1697477219064/work/dist/pandas-2.1.1-cp311-cp311-win_amd64.whl#sha256=1732f3b07ba52119320a2b01aa09f2627f6258176e492b728daf60efb4f4d78e
    - ﻿pandasql==0.7.3
    - ﻿plotly==5.17.0
    - ﻿plotly-express==0.4.1
    - ﻿pydeck==0.8.1b0
    - ﻿python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
    - ﻿python-dotenv==1.0.0
    - ﻿python-json-logger @ file:///C:/b/abs_cblnsm6puj/croot/python-json-logger_1683824130469/work
    - ﻿s3transfer==0.7.0
    - ﻿scikit-learn==1.3.2
    - ﻿scipy==1.11.3
    - ﻿seaborn @ file:///C:/ci_311/seaborn_1676446547861/work
    - ﻿streamlit==1.28.1
